apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
spec:
  dnsNames:
    - xyz.info
  secretName: letsencrypt-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer